# .alacritty.toml - alacritty dotfile
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import = ["~/.config/alacritty/themes/themes/gotham.toml"]
ipc_socket = true
live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "#ff0000"
duration = 400

[bell.command]
args = ["warning"]
program = "notify-send"

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "alacritty"

[font]
size = 14.0

[font.bold]
family = "iosevka"
style = "bold"

[font.bold_italic]
family = "iosevka"
style = "Bold Italic"

[font.italic]
family = "iosevka"
style = "Italic"

[font.normal]
family = "iosevka"

[font.offset]
x = 0
y = 0

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "google-chrome"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[mouse]
hide_when_typing = true

[scrolling]
history = 0
multiplier = 1

[shell]
args = ["--login"]
program = "/usr/bin/bash"

[window]
decorations = "none"
decorations_theme_variant = "Dark"
dynamic_padding = true
dynamic_title = true
opacity = 1.0
startup_mode = "Maximized"
title = "alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 100
lines = 32

[window.padding]
x = 0
y = 0

[window.position]
x = 0
y = 0
